Launcher
FRC-1294/frc2024-comp-software pull request #17
Opened 2024-02-01 02:36 UTC by chujiyang

The Launcher Subsystem incorporates two flywheel motors and one indexer motor.
Flywheel:

The velocity of the main and roller flywheels are set depending on different modes: speaker, amp, and off.

Indexer:

The indexer is ran when there is a note indexed, the launcher is ready (see below), and a driver toggle that allows notes to be indexed to the flywheel is on.
The launcher is determined to be ready when the difference between the set velocity and actual velocity is within a tolerance.
In the Launcher Constants file, there are temporary values for:

IDs for the main flywheel, roller flywheel, and indexer
PID values for V, P, I, D
Flywheel value tolerance
Max velocity for the flywheel motors

2024-02-06 04:22 UTC, AadityaAgni requested changes
Almost there!

2024-02-06 04:22 UTC, AadityaAgni commented on src/main/java/frc/robot/constants/LauncherConstants.java
> +  public static final int MAIN_FLYWHEEL_ID = 1; //TBD https://github.com/FRC-1294/frc2024/issues/241
Change the TBD to a "TODO:" so that it gets highlighted in code

2024-02-06 04:22 UTC, AadityaAgni commented on src/main/java/frc/robot/subsystems/LauncherSubsystem.java
> +    mRollerFlywheel.getConfigurator().apply(slotConfigs);
Set one motor as the follower of the other

2024-02-06 04:22 UTC, AadityaAgni commented on src/main/java/frc/robot/subsystems/LauncherSubsystem.java
> +    mRollerFlywheel.setControl(new VelocityVoltage(mDesiredVelocityMain).withSlot(0));
If you make one the follower, you don't have to do this. Alternatively, make sure to set inversions.

2024-02-06 04:22 UTC, AadityaAgni commented on vendordeps/Phoenix5.json
> +{
Delete Phoenix 5

2024-02-06 18:33 UTC, AadityaAgni approved these changes
LGTM!

2024-02-07 15:05 UTC, geeknoid commented
Can you take a look at the new Sonar issues and see if you can address a few of these before checkin?

2024-02-08 02:16 UTC, geeknoid approved these changes

2024-02-08 02:18 UTC, merged