Test All done
FRC-1294/frc2024-comp-software pull request #31
Opened 2024-02-24 20:32 UTC by Powerlax

Testing for Intake, Aiming, Launcher, and Swerve Subsystems.

2024-02-26 01:01 UTC, AadityaAgni requested changes
Lets speak later about what I was hoping from the testing framework

2024-02-26 01:01 UTC, AadityaAgni commented on src/main/java/frc/robot/commands/TestAll.java
> +    return true;
Why is the isFinished True? It will never run

2024-02-26 01:01 UTC, AadityaAgni commented on src/main/java/frc/robot/commands/TestAll.java
> +    new WaitCommand(5);
You never schedule any of these wait commands

2024-02-26 01:01 UTC, AadityaAgni commented on src/main/java/frc/robot/commands/TestAll.java
> +    mSwerve.setChassisSpeed(1, 0, 0, false,false);
Where is all of this run? There aren't any commands, just a function that sets stuff. This will run in one cycle and finish

2024-03-18 20:45 UTC, geeknoid approved these changes

2025-01-12 04:32 UTC, merged